/*
 * ArmsUpAndOutCommand.h
 *
 *  Created on: Feb 28, 2016
 *      Author: CougarRobotics
 */

#ifndef SRC_COMMANDS_ARMSUPANDOUTCOMMAND_H_
#define SRC_COMMANDS_ARMSUPANDOUTCOMMAND_H_

// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

#include "Commands/Subsystem.h"
#include "../Robot.h"

/**
 *
 *
 * @author ExampleAuthor
 */
class ArmsUpAndOutCommand : public Command {
	public:
		ArmsUpAndOutCommand();
		virtual void
		Initialize();
		virtual void
		Execute();
		virtual bool
		IsFinished();
		virtual void
		End();
		virtual void
		Interrupted();
};

#endif /* SRC_COMMANDS_ARMSUPANDOUTCOMMAND_H_ */
