// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

#include "RobotMap.h"
#include "LiveWindow/LiveWindow.h"

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=ALLOCATION
SpeedController* RobotMap::robotDriveTreadRightFront = NULL;
SpeedController* RobotMap::robotDriveTreadRightBack = NULL;
SpeedController* RobotMap::robotDriveTreadLeftFront = NULL;
SpeedController* RobotMap::robotDriveTreadLeftBack = NULL;
SpeedController* RobotMap::ballShooterSpinnerClockwise = NULL;
SpeedController* RobotMap::ballShooterSpinnerCounterclockwise = NULL;
Relay* RobotMap::ballShooterSpinnerSpringWinder = NULL;
Relay* RobotMap::lifter = NULL;
SpeedController* RobotMap::position = NULL;

RobotDrive* RobotMap::robotDrive41 = NULL;
RobotDrive* RobotMap::shooterAimingDevice = NULL;

AnalogPotentiometer* RobotMap::potentiometer = NULL;
AnalogAccelerometer* RobotMap::accelerometer = NULL;

// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=ALLOCATION

RobotMap::RobotMap()
		: gyro(GYRO) {
	gyro->InitGyro();
	gyro->Calibrate();
}

void RobotMap::init() {
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
	LiveWindow* lw = LiveWindow::GetInstance();

	//NOTE: This is where you set the where the wire on RoboRIO goes

	//Sensors
	accelerometer = new AnalogAccelerometer(ACCELEROMETER);
	potentiometer = new AnalogPotentiometer(POTENTIOMETER);
//	gyro = new AnalogGyro(GYRO);

//Drive
	robotDriveTreadRightFront = new Talon(FRONT_RIGHT);
	lw->AddActuator("Robot Drive" , "treadRightFront" ,	//NOTE 2-10-16: The mechanical people unplugged all of the wires on the RoboRIO, so they will ALL need to be RESET
	(Talon*) robotDriveTreadRightFront);

	robotDriveTreadRightBack = new Talon(BACK_RIGHT);
	lw->AddActuator("Robot Drive" , "treadRightBack" , (Talon*) robotDriveTreadRightBack);

	robotDriveTreadLeftFront = new Talon(FRONT_LEFT);
	lw->AddActuator("Robot Drive" , "treadLeftFront" , (Talon*) robotDriveTreadLeftFront);

	robotDriveTreadLeftBack = new Talon(BACK_LEFT);
	lw->AddActuator("Robot Drive" , "treadLeftBack" , (Talon*) robotDriveTreadLeftBack);

	robotDrive41 = new RobotDrive(robotDriveTreadLeftFront , robotDriveTreadLeftBack , robotDriveTreadRightFront , robotDriveTreadRightBack);

	robotDrive41->SetSafetyEnabled(true);
	robotDrive41->SetExpiration(0.1);
	robotDrive41->SetSensitivity(0.5);
	robotDrive41->SetMaxOutput(1.0);
	robotDrive41->SetInvertedMotor(RobotDrive::kFrontRightMotor , true);
	robotDrive41->SetInvertedMotor(RobotDrive::kRearRightMotor , true);

	//Ball Shooter
	ballShooterSpinnerClockwise = new Talon(SPINNER_CW);
	lw->AddActuator("Ball Shooter" , "clockwise spinner" , (Talon*) ballShooterSpinnerClockwise);

	ballShooterSpinnerCounterclockwise = new Talon(SPINNER_CCW);
	lw->AddActuator("Ball Shooter" , "clockwise spinner" , (Talon*) ballShooterSpinnerCounterclockwise);

	ballShooterSpinnerSpringWinder = new Relay(SPINNER_SPRING_WINDER);
	lw->AddActuator("Ball Shooter" , "spinner spring winder" , (Relay*) ballShooterSpinnerSpringWinder);

	shooterAimingDevice = new RobotDrive(ballShooterSpinnerClockwise , ballShooterSpinnerCounterclockwise , NULL , NULL);

	shooterAimingDevice->SetSafetyEnabled(true);
	shooterAimingDevice->SetExpiration(0.1);
	shooterAimingDevice->SetSensitivity(0.5);
	shooterAimingDevice->SetMaxOutput(0.5);
	shooterAimingDevice->SetInvertedMotor(RobotDrive::kRearLeftMotor , true);

	lifter = new Relay(LIFTER);
	lw->AddActuator("MCL" , "lifter" , (Relay*) lifter);

	position = new Talon(POSITION);
	lw->AddActuator("MCL" , "position" , (Talon*) position);

	// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
}
