// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

#ifndef ROBOTMAP_H
#define ROBOTMAP_H
#include "WPILib.h"

#define FRONT_RIGHT 0
#define FRONT_LEFT 0
#define BACK_RIGHT 0
#define BACK_LEFT 0

#define SPINNER_CW 0
#define SPINNER_CCW 0
#define SPINNER_SPRING_WINDER 0

#define LIFTER 0
#define POSITION 0

#define POTENTIOMETER 0
#define ACCELEROMETER 0
#define COMPASS 0
#define GYRO 0

/**
 * The RobotMap is a mapping from the ports sensors and actuators are wired into
 * to a variable name. This provides flexibility changing wiring, makes checking
 * the wiring easier and significantly reduces the number of magic numbers
 * floating around.
 */
class RobotMap {
	public:
		// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
		static SpeedController* robotDriveTreadRightFront;
		static SpeedController* robotDriveTreadRightBack;
		static SpeedController* robotDriveTreadLeftFront;
		static SpeedController* robotDriveTreadLeftBack;

		static SpeedController* ballShooterSpinnerClockwise;
		static SpeedController* ballShooterSpinnerCounterclockwise;
		static SpeedController* ballShooterSpinnerSpringWinder;

		static SpeedController* lifter;
		static SpeedController* position;

		static RobotDrive* robotDrive41;
		static RobotDrive* shooter;

		static AnalogPotentiometer* potentiometer;
		static AnalogAccelerometer* accelerometer;
		static AnalogGyro* gyro;

//		static DigitalInput* compass;
		// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

		static void init();
};
#endif
