// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

#ifndef ROBOTMAP_H
#define ROBOTMAP_H

#include "WPILib.h"
#include "AnalogGyro.h"
#include <Relay.h>

#ifndef NULL
#define NULL   ((void *) 0)
#endif

#define FRONT_RIGHT 7
#define FRONT_LEFT 5
#define BACK_RIGHT 6
#define BACK_LEFT 8

#define SPINNER_CW 2
#define SPINNER_CCW 3	// TODO: spinner cw and spinner ccw might be swapped
#define SPINNER_SPRING_WINDER 1

#define SCALE_TOWER 0 //TODO: GET PORT
#define ARMS_UP_AND_OUT 1
#define HOOK_RELEASE 0 //TODO: GET PORT
#define POSITION 4

//TODO: Get the ports of all the defines below
//Sensors
#define PORT_POTENTIOMETER 1
#define PORT_ACCELEROMETER 2
#define PORT_ULTRASONIC_PING 3 // TODO: Get port number
#define PORT_ULTRASONIC_ECHO PORT_ULTRASONIC_PING // TODO: Get port number
#define PORT_GYRO 0

//Limit Switches
#define L_SPINNER_SPRING_WINDER 0
#define L_SAD_POS_BASELINE 0

//Height Counter (pulses)
#define HEIGHT_COUNTER 0

/**
 *The RobotMap is a mapping from the ports sensors and actuators are wired into
 *to a variable name. This provides flexibility changing wiring, makes checking
 *the wiring easier and significantly reduces the number of magic numbers
 *floating around.
 */
class RobotMap {
	private:
		RobotMap ();
	public:
		static RobotMap *robotMap;
		// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
		static SpeedController *robotDriveTreadRightFront;
		static SpeedController *robotDriveTreadRightBack;
		static SpeedController *robotDriveTreadLeftFront;
		static SpeedController *robotDriveTreadLeftBack;

		static SpeedController *ballShooterSpinnerClockwise;
		static SpeedController *ballShooterSpinnerCounterclockwise;
		static SpeedController *shooterAimingDevice; // SAD = Shooter Aiming Device
		static Relay *ballShooterSpinnerSpringWinder;

		static SpeedController *scaleTower;
		static Relay *armsUpAndOut;
		static SpeedController *position;

		static RobotDrive *robotDrive41;
//		static RobotDrive *shooting;

		static AnalogPotentiometer *potentiometer;
		static BuiltInAccelerometer *accelerometer;
		static Ultrasonic *ultrasonic;

		static DigitalInput *limitSpinnerSpringWinder;
		static DigitalInput *limitSADPosBaseline;
		static AnalogTrigger *heightCounter;

		AnalogGyro *gyro;
		// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

		static void
		init ();
};
#endif
